# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server/CMakeFiles /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named autoli

# Build rule for target.
autoli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autoli
.PHONY : autoli

# fast build rule for target.
autoli/fast:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/build
.PHONY : autoli/fast

autoli/config.o: autoli/config.cc.o

.PHONY : autoli/config.o

# target to build an object file
autoli/config.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/config.cc.o
.PHONY : autoli/config.cc.o

autoli/config.i: autoli/config.cc.i

.PHONY : autoli/config.i

# target to preprocess a source file
autoli/config.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/config.cc.i
.PHONY : autoli/config.cc.i

autoli/config.s: autoli/config.cc.s

.PHONY : autoli/config.s

# target to generate assembly for a file
autoli/config.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/config.cc.s
.PHONY : autoli/config.cc.s

autoli/fiber.o: autoli/fiber.cc.o

.PHONY : autoli/fiber.o

# target to build an object file
autoli/fiber.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fiber.cc.o
.PHONY : autoli/fiber.cc.o

autoli/fiber.i: autoli/fiber.cc.i

.PHONY : autoli/fiber.i

# target to preprocess a source file
autoli/fiber.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fiber.cc.i
.PHONY : autoli/fiber.cc.i

autoli/fiber.s: autoli/fiber.cc.s

.PHONY : autoli/fiber.s

# target to generate assembly for a file
autoli/fiber.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fiber.cc.s
.PHONY : autoli/fiber.cc.s

autoli/iomanager.o: autoli/iomanager.cc.o

.PHONY : autoli/iomanager.o

# target to build an object file
autoli/iomanager.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/iomanager.cc.o
.PHONY : autoli/iomanager.cc.o

autoli/iomanager.i: autoli/iomanager.cc.i

.PHONY : autoli/iomanager.i

# target to preprocess a source file
autoli/iomanager.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/iomanager.cc.i
.PHONY : autoli/iomanager.cc.i

autoli/iomanager.s: autoli/iomanager.cc.s

.PHONY : autoli/iomanager.s

# target to generate assembly for a file
autoli/iomanager.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/iomanager.cc.s
.PHONY : autoli/iomanager.cc.s

autoli/log.o: autoli/log.cc.o

.PHONY : autoli/log.o

# target to build an object file
autoli/log.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/log.cc.o
.PHONY : autoli/log.cc.o

autoli/log.i: autoli/log.cc.i

.PHONY : autoli/log.i

# target to preprocess a source file
autoli/log.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/log.cc.i
.PHONY : autoli/log.cc.i

autoli/log.s: autoli/log.cc.s

.PHONY : autoli/log.s

# target to generate assembly for a file
autoli/log.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/log.cc.s
.PHONY : autoli/log.cc.s

autoli/mutex.o: autoli/mutex.cc.o

.PHONY : autoli/mutex.o

# target to build an object file
autoli/mutex.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/mutex.cc.o
.PHONY : autoli/mutex.cc.o

autoli/mutex.i: autoli/mutex.cc.i

.PHONY : autoli/mutex.i

# target to preprocess a source file
autoli/mutex.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/mutex.cc.i
.PHONY : autoli/mutex.cc.i

autoli/mutex.s: autoli/mutex.cc.s

.PHONY : autoli/mutex.s

# target to generate assembly for a file
autoli/mutex.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/mutex.cc.s
.PHONY : autoli/mutex.cc.s

autoli/scheduler.o: autoli/scheduler.cc.o

.PHONY : autoli/scheduler.o

# target to build an object file
autoli/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/scheduler.cc.o
.PHONY : autoli/scheduler.cc.o

autoli/scheduler.i: autoli/scheduler.cc.i

.PHONY : autoli/scheduler.i

# target to preprocess a source file
autoli/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/scheduler.cc.i
.PHONY : autoli/scheduler.cc.i

autoli/scheduler.s: autoli/scheduler.cc.s

.PHONY : autoli/scheduler.s

# target to generate assembly for a file
autoli/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/scheduler.cc.s
.PHONY : autoli/scheduler.cc.s

autoli/thread.o: autoli/thread.cc.o

.PHONY : autoli/thread.o

# target to build an object file
autoli/thread.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/thread.cc.o
.PHONY : autoli/thread.cc.o

autoli/thread.i: autoli/thread.cc.i

.PHONY : autoli/thread.i

# target to preprocess a source file
autoli/thread.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/thread.cc.i
.PHONY : autoli/thread.cc.i

autoli/thread.s: autoli/thread.cc.s

.PHONY : autoli/thread.s

# target to generate assembly for a file
autoli/thread.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/thread.cc.s
.PHONY : autoli/thread.cc.s

autoli/timer.o: autoli/timer.cc.o

.PHONY : autoli/timer.o

# target to build an object file
autoli/timer.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/timer.cc.o
.PHONY : autoli/timer.cc.o

autoli/timer.i: autoli/timer.cc.i

.PHONY : autoli/timer.i

# target to preprocess a source file
autoli/timer.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/timer.cc.i
.PHONY : autoli/timer.cc.i

autoli/timer.s: autoli/timer.cc.s

.PHONY : autoli/timer.s

# target to generate assembly for a file
autoli/timer.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/timer.cc.s
.PHONY : autoli/timer.cc.s

autoli/util.o: autoli/util.cc.o

.PHONY : autoli/util.o

# target to build an object file
autoli/util.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/util.cc.o
.PHONY : autoli/util.cc.o

autoli/util.i: autoli/util.cc.i

.PHONY : autoli/util.i

# target to preprocess a source file
autoli/util.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/util.cc.i
.PHONY : autoli/util.cc.i

autoli/util.s: autoli/util.cc.s

.PHONY : autoli/util.s

# target to generate assembly for a file
autoli/util.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/util.cc.s
.PHONY : autoli/util.cc.s

tests/test.o: tests/test.cc.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

tests/test_util.o: tests/test_util.cc.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cc.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.o
.PHONY : tests/test_util.cc.o

tests/test_util.i: tests/test_util.cc.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cc.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.i
.PHONY : tests/test_util.cc.i

tests/test_util.s: tests/test_util.cc.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cc.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.s
.PHONY : tests/test_util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_iomanager"
	@echo "... test_fiber"
	@echo "... rebuild_cache"
	@echo "... test_util"
	@echo "... test_config"
	@echo "... edit_cache"
	@echo "... test_thread"
	@echo "... test"
	@echo "... test_scheduler"
	@echo "... autoli"
	@echo "... autoli/config.o"
	@echo "... autoli/config.i"
	@echo "... autoli/config.s"
	@echo "... autoli/fiber.o"
	@echo "... autoli/fiber.i"
	@echo "... autoli/fiber.s"
	@echo "... autoli/iomanager.o"
	@echo "... autoli/iomanager.i"
	@echo "... autoli/iomanager.s"
	@echo "... autoli/log.o"
	@echo "... autoli/log.i"
	@echo "... autoli/log.s"
	@echo "... autoli/mutex.o"
	@echo "... autoli/mutex.i"
	@echo "... autoli/mutex.s"
	@echo "... autoli/scheduler.o"
	@echo "... autoli/scheduler.i"
	@echo "... autoli/scheduler.s"
	@echo "... autoli/thread.o"
	@echo "... autoli/thread.i"
	@echo "... autoli/thread.s"
	@echo "... autoli/timer.o"
	@echo "... autoli/timer.i"
	@echo "... autoli/timer.s"
	@echo "... autoli/util.o"
	@echo "... autoli/util.i"
	@echo "... autoli/util.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

