# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server/CMakeFiles /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/llaron/7E96ADB696AD6F79/代码/高性能服务器/autoli-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_uri

# Build rule for target.
test_uri: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_uri
.PHONY : test_uri

# fast build rule for target.
test_uri/fast:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/build
.PHONY : test_uri/fast

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test_tcp_server

# Build rule for target.
test_tcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp_server
.PHONY : test_tcp_server

# fast build rule for target.
test_tcp_server/fast:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/build
.PHONY : test_tcp_server/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named echo_server_udp

# Build rule for target.
echo_server_udp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server_udp
.PHONY : echo_server_udp

# fast build rule for target.
echo_server_udp/fast:
	$(MAKE) -f CMakeFiles/echo_server_udp.dir/build.make CMakeFiles/echo_server_udp.dir/build
.PHONY : echo_server_udp/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named echo_udp_client

# Build rule for target.
echo_udp_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_udp_client
.PHONY : echo_udp_client

# fast build rule for target.
echo_udp_client/fast:
	$(MAKE) -f CMakeFiles/echo_udp_client.dir/build.make CMakeFiles/echo_udp_client.dir/build
.PHONY : echo_udp_client/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named autoli

# Build rule for target.
autoli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autoli
.PHONY : autoli

# fast build rule for target.
autoli/fast:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/build
.PHONY : autoli/fast

#=============================================================================
# Target rules for targets named test_http

# Build rule for target.
test_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http
.PHONY : test_http

# fast build rule for target.
test_http/fast:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/build
.PHONY : test_http/fast

autoli/address.o: autoli/address.cc.o

.PHONY : autoli/address.o

# target to build an object file
autoli/address.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/address.cc.o
.PHONY : autoli/address.cc.o

autoli/address.i: autoli/address.cc.i

.PHONY : autoli/address.i

# target to preprocess a source file
autoli/address.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/address.cc.i
.PHONY : autoli/address.cc.i

autoli/address.s: autoli/address.cc.s

.PHONY : autoli/address.s

# target to generate assembly for a file
autoli/address.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/address.cc.s
.PHONY : autoli/address.cc.s

autoli/bytearray.o: autoli/bytearray.cc.o

.PHONY : autoli/bytearray.o

# target to build an object file
autoli/bytearray.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/bytearray.cc.o
.PHONY : autoli/bytearray.cc.o

autoli/bytearray.i: autoli/bytearray.cc.i

.PHONY : autoli/bytearray.i

# target to preprocess a source file
autoli/bytearray.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/bytearray.cc.i
.PHONY : autoli/bytearray.cc.i

autoli/bytearray.s: autoli/bytearray.cc.s

.PHONY : autoli/bytearray.s

# target to generate assembly for a file
autoli/bytearray.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/bytearray.cc.s
.PHONY : autoli/bytearray.cc.s

autoli/config.o: autoli/config.cc.o

.PHONY : autoli/config.o

# target to build an object file
autoli/config.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/config.cc.o
.PHONY : autoli/config.cc.o

autoli/config.i: autoli/config.cc.i

.PHONY : autoli/config.i

# target to preprocess a source file
autoli/config.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/config.cc.i
.PHONY : autoli/config.cc.i

autoli/config.s: autoli/config.cc.s

.PHONY : autoli/config.s

# target to generate assembly for a file
autoli/config.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/config.cc.s
.PHONY : autoli/config.cc.s

autoli/fd_manager.o: autoli/fd_manager.cc.o

.PHONY : autoli/fd_manager.o

# target to build an object file
autoli/fd_manager.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fd_manager.cc.o
.PHONY : autoli/fd_manager.cc.o

autoli/fd_manager.i: autoli/fd_manager.cc.i

.PHONY : autoli/fd_manager.i

# target to preprocess a source file
autoli/fd_manager.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fd_manager.cc.i
.PHONY : autoli/fd_manager.cc.i

autoli/fd_manager.s: autoli/fd_manager.cc.s

.PHONY : autoli/fd_manager.s

# target to generate assembly for a file
autoli/fd_manager.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fd_manager.cc.s
.PHONY : autoli/fd_manager.cc.s

autoli/fiber.o: autoli/fiber.cc.o

.PHONY : autoli/fiber.o

# target to build an object file
autoli/fiber.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fiber.cc.o
.PHONY : autoli/fiber.cc.o

autoli/fiber.i: autoli/fiber.cc.i

.PHONY : autoli/fiber.i

# target to preprocess a source file
autoli/fiber.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fiber.cc.i
.PHONY : autoli/fiber.cc.i

autoli/fiber.s: autoli/fiber.cc.s

.PHONY : autoli/fiber.s

# target to generate assembly for a file
autoli/fiber.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/fiber.cc.s
.PHONY : autoli/fiber.cc.s

autoli/hook.o: autoli/hook.cc.o

.PHONY : autoli/hook.o

# target to build an object file
autoli/hook.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/hook.cc.o
.PHONY : autoli/hook.cc.o

autoli/hook.i: autoli/hook.cc.i

.PHONY : autoli/hook.i

# target to preprocess a source file
autoli/hook.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/hook.cc.i
.PHONY : autoli/hook.cc.i

autoli/hook.s: autoli/hook.cc.s

.PHONY : autoli/hook.s

# target to generate assembly for a file
autoli/hook.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/hook.cc.s
.PHONY : autoli/hook.cc.s

autoli/http/http.o: autoli/http/http.cc.o

.PHONY : autoli/http/http.o

# target to build an object file
autoli/http/http.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http.cc.o
.PHONY : autoli/http/http.cc.o

autoli/http/http.i: autoli/http/http.cc.i

.PHONY : autoli/http/http.i

# target to preprocess a source file
autoli/http/http.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http.cc.i
.PHONY : autoli/http/http.cc.i

autoli/http/http.s: autoli/http/http.cc.s

.PHONY : autoli/http/http.s

# target to generate assembly for a file
autoli/http/http.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http.cc.s
.PHONY : autoli/http/http.cc.s

autoli/http/http11_parser.rl.o: autoli/http/http11_parser.rl.cc.o

.PHONY : autoli/http/http11_parser.rl.o

# target to build an object file
autoli/http/http11_parser.rl.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http11_parser.rl.cc.o
.PHONY : autoli/http/http11_parser.rl.cc.o

autoli/http/http11_parser.rl.i: autoli/http/http11_parser.rl.cc.i

.PHONY : autoli/http/http11_parser.rl.i

# target to preprocess a source file
autoli/http/http11_parser.rl.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http11_parser.rl.cc.i
.PHONY : autoli/http/http11_parser.rl.cc.i

autoli/http/http11_parser.rl.s: autoli/http/http11_parser.rl.cc.s

.PHONY : autoli/http/http11_parser.rl.s

# target to generate assembly for a file
autoli/http/http11_parser.rl.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http11_parser.rl.cc.s
.PHONY : autoli/http/http11_parser.rl.cc.s

autoli/http/http_connection.o: autoli/http/http_connection.cc.o

.PHONY : autoli/http/http_connection.o

# target to build an object file
autoli/http/http_connection.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_connection.cc.o
.PHONY : autoli/http/http_connection.cc.o

autoli/http/http_connection.i: autoli/http/http_connection.cc.i

.PHONY : autoli/http/http_connection.i

# target to preprocess a source file
autoli/http/http_connection.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_connection.cc.i
.PHONY : autoli/http/http_connection.cc.i

autoli/http/http_connection.s: autoli/http/http_connection.cc.s

.PHONY : autoli/http/http_connection.s

# target to generate assembly for a file
autoli/http/http_connection.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_connection.cc.s
.PHONY : autoli/http/http_connection.cc.s

autoli/http/http_parser.o: autoli/http/http_parser.cc.o

.PHONY : autoli/http/http_parser.o

# target to build an object file
autoli/http/http_parser.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_parser.cc.o
.PHONY : autoli/http/http_parser.cc.o

autoli/http/http_parser.i: autoli/http/http_parser.cc.i

.PHONY : autoli/http/http_parser.i

# target to preprocess a source file
autoli/http/http_parser.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_parser.cc.i
.PHONY : autoli/http/http_parser.cc.i

autoli/http/http_parser.s: autoli/http/http_parser.cc.s

.PHONY : autoli/http/http_parser.s

# target to generate assembly for a file
autoli/http/http_parser.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_parser.cc.s
.PHONY : autoli/http/http_parser.cc.s

autoli/http/http_server.o: autoli/http/http_server.cc.o

.PHONY : autoli/http/http_server.o

# target to build an object file
autoli/http/http_server.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_server.cc.o
.PHONY : autoli/http/http_server.cc.o

autoli/http/http_server.i: autoli/http/http_server.cc.i

.PHONY : autoli/http/http_server.i

# target to preprocess a source file
autoli/http/http_server.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_server.cc.i
.PHONY : autoli/http/http_server.cc.i

autoli/http/http_server.s: autoli/http/http_server.cc.s

.PHONY : autoli/http/http_server.s

# target to generate assembly for a file
autoli/http/http_server.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_server.cc.s
.PHONY : autoli/http/http_server.cc.s

autoli/http/http_session.o: autoli/http/http_session.cc.o

.PHONY : autoli/http/http_session.o

# target to build an object file
autoli/http/http_session.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_session.cc.o
.PHONY : autoli/http/http_session.cc.o

autoli/http/http_session.i: autoli/http/http_session.cc.i

.PHONY : autoli/http/http_session.i

# target to preprocess a source file
autoli/http/http_session.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_session.cc.i
.PHONY : autoli/http/http_session.cc.i

autoli/http/http_session.s: autoli/http/http_session.cc.s

.PHONY : autoli/http/http_session.s

# target to generate assembly for a file
autoli/http/http_session.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/http_session.cc.s
.PHONY : autoli/http/http_session.cc.s

autoli/http/httpclient_parser.rl.o: autoli/http/httpclient_parser.rl.cc.o

.PHONY : autoli/http/httpclient_parser.rl.o

# target to build an object file
autoli/http/httpclient_parser.rl.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/httpclient_parser.rl.cc.o
.PHONY : autoli/http/httpclient_parser.rl.cc.o

autoli/http/httpclient_parser.rl.i: autoli/http/httpclient_parser.rl.cc.i

.PHONY : autoli/http/httpclient_parser.rl.i

# target to preprocess a source file
autoli/http/httpclient_parser.rl.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/httpclient_parser.rl.cc.i
.PHONY : autoli/http/httpclient_parser.rl.cc.i

autoli/http/httpclient_parser.rl.s: autoli/http/httpclient_parser.rl.cc.s

.PHONY : autoli/http/httpclient_parser.rl.s

# target to generate assembly for a file
autoli/http/httpclient_parser.rl.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/httpclient_parser.rl.cc.s
.PHONY : autoli/http/httpclient_parser.rl.cc.s

autoli/http/servlet.o: autoli/http/servlet.cc.o

.PHONY : autoli/http/servlet.o

# target to build an object file
autoli/http/servlet.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/servlet.cc.o
.PHONY : autoli/http/servlet.cc.o

autoli/http/servlet.i: autoli/http/servlet.cc.i

.PHONY : autoli/http/servlet.i

# target to preprocess a source file
autoli/http/servlet.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/servlet.cc.i
.PHONY : autoli/http/servlet.cc.i

autoli/http/servlet.s: autoli/http/servlet.cc.s

.PHONY : autoli/http/servlet.s

# target to generate assembly for a file
autoli/http/servlet.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/http/servlet.cc.s
.PHONY : autoli/http/servlet.cc.s

autoli/iomanager.o: autoli/iomanager.cc.o

.PHONY : autoli/iomanager.o

# target to build an object file
autoli/iomanager.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/iomanager.cc.o
.PHONY : autoli/iomanager.cc.o

autoli/iomanager.i: autoli/iomanager.cc.i

.PHONY : autoli/iomanager.i

# target to preprocess a source file
autoli/iomanager.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/iomanager.cc.i
.PHONY : autoli/iomanager.cc.i

autoli/iomanager.s: autoli/iomanager.cc.s

.PHONY : autoli/iomanager.s

# target to generate assembly for a file
autoli/iomanager.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/iomanager.cc.s
.PHONY : autoli/iomanager.cc.s

autoli/log.o: autoli/log.cc.o

.PHONY : autoli/log.o

# target to build an object file
autoli/log.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/log.cc.o
.PHONY : autoli/log.cc.o

autoli/log.i: autoli/log.cc.i

.PHONY : autoli/log.i

# target to preprocess a source file
autoli/log.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/log.cc.i
.PHONY : autoli/log.cc.i

autoli/log.s: autoli/log.cc.s

.PHONY : autoli/log.s

# target to generate assembly for a file
autoli/log.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/log.cc.s
.PHONY : autoli/log.cc.s

autoli/mutex.o: autoli/mutex.cc.o

.PHONY : autoli/mutex.o

# target to build an object file
autoli/mutex.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/mutex.cc.o
.PHONY : autoli/mutex.cc.o

autoli/mutex.i: autoli/mutex.cc.i

.PHONY : autoli/mutex.i

# target to preprocess a source file
autoli/mutex.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/mutex.cc.i
.PHONY : autoli/mutex.cc.i

autoli/mutex.s: autoli/mutex.cc.s

.PHONY : autoli/mutex.s

# target to generate assembly for a file
autoli/mutex.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/mutex.cc.s
.PHONY : autoli/mutex.cc.s

autoli/scheduler.o: autoli/scheduler.cc.o

.PHONY : autoli/scheduler.o

# target to build an object file
autoli/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/scheduler.cc.o
.PHONY : autoli/scheduler.cc.o

autoli/scheduler.i: autoli/scheduler.cc.i

.PHONY : autoli/scheduler.i

# target to preprocess a source file
autoli/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/scheduler.cc.i
.PHONY : autoli/scheduler.cc.i

autoli/scheduler.s: autoli/scheduler.cc.s

.PHONY : autoli/scheduler.s

# target to generate assembly for a file
autoli/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/scheduler.cc.s
.PHONY : autoli/scheduler.cc.s

autoli/socket.o: autoli/socket.cc.o

.PHONY : autoli/socket.o

# target to build an object file
autoli/socket.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/socket.cc.o
.PHONY : autoli/socket.cc.o

autoli/socket.i: autoli/socket.cc.i

.PHONY : autoli/socket.i

# target to preprocess a source file
autoli/socket.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/socket.cc.i
.PHONY : autoli/socket.cc.i

autoli/socket.s: autoli/socket.cc.s

.PHONY : autoli/socket.s

# target to generate assembly for a file
autoli/socket.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/socket.cc.s
.PHONY : autoli/socket.cc.s

autoli/stream.o: autoli/stream.cc.o

.PHONY : autoli/stream.o

# target to build an object file
autoli/stream.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/stream.cc.o
.PHONY : autoli/stream.cc.o

autoli/stream.i: autoli/stream.cc.i

.PHONY : autoli/stream.i

# target to preprocess a source file
autoli/stream.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/stream.cc.i
.PHONY : autoli/stream.cc.i

autoli/stream.s: autoli/stream.cc.s

.PHONY : autoli/stream.s

# target to generate assembly for a file
autoli/stream.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/stream.cc.s
.PHONY : autoli/stream.cc.s

autoli/streams/socket_stream.o: autoli/streams/socket_stream.cc.o

.PHONY : autoli/streams/socket_stream.o

# target to build an object file
autoli/streams/socket_stream.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/streams/socket_stream.cc.o
.PHONY : autoli/streams/socket_stream.cc.o

autoli/streams/socket_stream.i: autoli/streams/socket_stream.cc.i

.PHONY : autoli/streams/socket_stream.i

# target to preprocess a source file
autoli/streams/socket_stream.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/streams/socket_stream.cc.i
.PHONY : autoli/streams/socket_stream.cc.i

autoli/streams/socket_stream.s: autoli/streams/socket_stream.cc.s

.PHONY : autoli/streams/socket_stream.s

# target to generate assembly for a file
autoli/streams/socket_stream.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/streams/socket_stream.cc.s
.PHONY : autoli/streams/socket_stream.cc.s

autoli/streams/zlib_stream.o: autoli/streams/zlib_stream.cc.o

.PHONY : autoli/streams/zlib_stream.o

# target to build an object file
autoli/streams/zlib_stream.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/streams/zlib_stream.cc.o
.PHONY : autoli/streams/zlib_stream.cc.o

autoli/streams/zlib_stream.i: autoli/streams/zlib_stream.cc.i

.PHONY : autoli/streams/zlib_stream.i

# target to preprocess a source file
autoli/streams/zlib_stream.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/streams/zlib_stream.cc.i
.PHONY : autoli/streams/zlib_stream.cc.i

autoli/streams/zlib_stream.s: autoli/streams/zlib_stream.cc.s

.PHONY : autoli/streams/zlib_stream.s

# target to generate assembly for a file
autoli/streams/zlib_stream.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/streams/zlib_stream.cc.s
.PHONY : autoli/streams/zlib_stream.cc.s

autoli/tcp_server.o: autoli/tcp_server.cc.o

.PHONY : autoli/tcp_server.o

# target to build an object file
autoli/tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/tcp_server.cc.o
.PHONY : autoli/tcp_server.cc.o

autoli/tcp_server.i: autoli/tcp_server.cc.i

.PHONY : autoli/tcp_server.i

# target to preprocess a source file
autoli/tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/tcp_server.cc.i
.PHONY : autoli/tcp_server.cc.i

autoli/tcp_server.s: autoli/tcp_server.cc.s

.PHONY : autoli/tcp_server.s

# target to generate assembly for a file
autoli/tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/tcp_server.cc.s
.PHONY : autoli/tcp_server.cc.s

autoli/thread.o: autoli/thread.cc.o

.PHONY : autoli/thread.o

# target to build an object file
autoli/thread.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/thread.cc.o
.PHONY : autoli/thread.cc.o

autoli/thread.i: autoli/thread.cc.i

.PHONY : autoli/thread.i

# target to preprocess a source file
autoli/thread.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/thread.cc.i
.PHONY : autoli/thread.cc.i

autoli/thread.s: autoli/thread.cc.s

.PHONY : autoli/thread.s

# target to generate assembly for a file
autoli/thread.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/thread.cc.s
.PHONY : autoli/thread.cc.s

autoli/timer.o: autoli/timer.cc.o

.PHONY : autoli/timer.o

# target to build an object file
autoli/timer.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/timer.cc.o
.PHONY : autoli/timer.cc.o

autoli/timer.i: autoli/timer.cc.i

.PHONY : autoli/timer.i

# target to preprocess a source file
autoli/timer.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/timer.cc.i
.PHONY : autoli/timer.cc.i

autoli/timer.s: autoli/timer.cc.s

.PHONY : autoli/timer.s

# target to generate assembly for a file
autoli/timer.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/timer.cc.s
.PHONY : autoli/timer.cc.s

autoli/uri.rl.o: autoli/uri.rl.cc.o

.PHONY : autoli/uri.rl.o

# target to build an object file
autoli/uri.rl.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/uri.rl.cc.o
.PHONY : autoli/uri.rl.cc.o

autoli/uri.rl.i: autoli/uri.rl.cc.i

.PHONY : autoli/uri.rl.i

# target to preprocess a source file
autoli/uri.rl.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/uri.rl.cc.i
.PHONY : autoli/uri.rl.cc.i

autoli/uri.rl.s: autoli/uri.rl.cc.s

.PHONY : autoli/uri.rl.s

# target to generate assembly for a file
autoli/uri.rl.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/uri.rl.cc.s
.PHONY : autoli/uri.rl.cc.s

autoli/util.o: autoli/util.cc.o

.PHONY : autoli/util.o

# target to build an object file
autoli/util.cc.o:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/util.cc.o
.PHONY : autoli/util.cc.o

autoli/util.i: autoli/util.cc.i

.PHONY : autoli/util.i

# target to preprocess a source file
autoli/util.cc.i:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/util.cc.i
.PHONY : autoli/util.cc.i

autoli/util.s: autoli/util.cc.s

.PHONY : autoli/util.s

# target to generate assembly for a file
autoli/util.cc.s:
	$(MAKE) -f CMakeFiles/autoli.dir/build.make CMakeFiles/autoli.dir/autoli/util.cc.s
.PHONY : autoli/util.cc.s

examples/echo_server.o: examples/echo_server.cc.o

.PHONY : examples/echo_server.o

# target to build an object file
examples/echo_server.cc.o:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.o
.PHONY : examples/echo_server.cc.o

examples/echo_server.i: examples/echo_server.cc.i

.PHONY : examples/echo_server.i

# target to preprocess a source file
examples/echo_server.cc.i:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.i
.PHONY : examples/echo_server.cc.i

examples/echo_server.s: examples/echo_server.cc.s

.PHONY : examples/echo_server.s

# target to generate assembly for a file
examples/echo_server.cc.s:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.s
.PHONY : examples/echo_server.cc.s

examples/echo_server_udp.o: examples/echo_server_udp.cc.o

.PHONY : examples/echo_server_udp.o

# target to build an object file
examples/echo_server_udp.cc.o:
	$(MAKE) -f CMakeFiles/echo_server_udp.dir/build.make CMakeFiles/echo_server_udp.dir/examples/echo_server_udp.cc.o
.PHONY : examples/echo_server_udp.cc.o

examples/echo_server_udp.i: examples/echo_server_udp.cc.i

.PHONY : examples/echo_server_udp.i

# target to preprocess a source file
examples/echo_server_udp.cc.i:
	$(MAKE) -f CMakeFiles/echo_server_udp.dir/build.make CMakeFiles/echo_server_udp.dir/examples/echo_server_udp.cc.i
.PHONY : examples/echo_server_udp.cc.i

examples/echo_server_udp.s: examples/echo_server_udp.cc.s

.PHONY : examples/echo_server_udp.s

# target to generate assembly for a file
examples/echo_server_udp.cc.s:
	$(MAKE) -f CMakeFiles/echo_server_udp.dir/build.make CMakeFiles/echo_server_udp.dir/examples/echo_server_udp.cc.s
.PHONY : examples/echo_server_udp.cc.s

examples/echo_udp_client.o: examples/echo_udp_client.cc.o

.PHONY : examples/echo_udp_client.o

# target to build an object file
examples/echo_udp_client.cc.o:
	$(MAKE) -f CMakeFiles/echo_udp_client.dir/build.make CMakeFiles/echo_udp_client.dir/examples/echo_udp_client.cc.o
.PHONY : examples/echo_udp_client.cc.o

examples/echo_udp_client.i: examples/echo_udp_client.cc.i

.PHONY : examples/echo_udp_client.i

# target to preprocess a source file
examples/echo_udp_client.cc.i:
	$(MAKE) -f CMakeFiles/echo_udp_client.dir/build.make CMakeFiles/echo_udp_client.dir/examples/echo_udp_client.cc.i
.PHONY : examples/echo_udp_client.cc.i

examples/echo_udp_client.s: examples/echo_udp_client.cc.s

.PHONY : examples/echo_udp_client.s

# target to generate assembly for a file
examples/echo_udp_client.cc.s:
	$(MAKE) -f CMakeFiles/echo_udp_client.dir/build.make CMakeFiles/echo_udp_client.dir/examples/echo_udp_client.cc.s
.PHONY : examples/echo_udp_client.cc.s

tests/test.o: tests/test.cc.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_address.o: tests/test_address.cc.o

.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cc.o:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.o
.PHONY : tests/test_address.cc.o

tests/test_address.i: tests/test_address.cc.i

.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cc.i:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.i
.PHONY : tests/test_address.cc.i

tests/test_address.s: tests/test_address.cc.s

.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cc.s:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.s
.PHONY : tests/test_address.cc.s

tests/test_bytearray.o: tests/test_bytearray.cc.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cc.o:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.o
.PHONY : tests/test_bytearray.cc.o

tests/test_bytearray.i: tests/test_bytearray.cc.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cc.i:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.i
.PHONY : tests/test_bytearray.cc.i

tests/test_bytearray.s: tests/test_bytearray.cc.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cc.s:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.s
.PHONY : tests/test_bytearray.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_hook.o: tests/test_hook.cc.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cc.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.o
.PHONY : tests/test_hook.cc.o

tests/test_hook.i: tests/test_hook.cc.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cc.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.i
.PHONY : tests/test_hook.cc.i

tests/test_hook.s: tests/test_hook.cc.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cc.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.s
.PHONY : tests/test_hook.cc.s

tests/test_http.o: tests/test_http.cc.o

.PHONY : tests/test_http.o

# target to build an object file
tests/test_http.cc.o:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.o
.PHONY : tests/test_http.cc.o

tests/test_http.i: tests/test_http.cc.i

.PHONY : tests/test_http.i

# target to preprocess a source file
tests/test_http.cc.i:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.i
.PHONY : tests/test_http.cc.i

tests/test_http.s: tests/test_http.cc.s

.PHONY : tests/test_http.s

# target to generate assembly for a file
tests/test_http.cc.s:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.s
.PHONY : tests/test_http.cc.s

tests/test_http_connection.o: tests/test_http_connection.cc.o

.PHONY : tests/test_http_connection.o

# target to build an object file
tests/test_http_connection.cc.o:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.o
.PHONY : tests/test_http_connection.cc.o

tests/test_http_connection.i: tests/test_http_connection.cc.i

.PHONY : tests/test_http_connection.i

# target to preprocess a source file
tests/test_http_connection.cc.i:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.i
.PHONY : tests/test_http_connection.cc.i

tests/test_http_connection.s: tests/test_http_connection.cc.s

.PHONY : tests/test_http_connection.s

# target to generate assembly for a file
tests/test_http_connection.cc.s:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.s
.PHONY : tests/test_http_connection.cc.s

tests/test_http_parser.o: tests/test_http_parser.cc.o

.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cc.o:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.o
.PHONY : tests/test_http_parser.cc.o

tests/test_http_parser.i: tests/test_http_parser.cc.i

.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cc.i:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.i
.PHONY : tests/test_http_parser.cc.i

tests/test_http_parser.s: tests/test_http_parser.cc.s

.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cc.s:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.s
.PHONY : tests/test_http_parser.cc.s

tests/test_http_server.o: tests/test_http_server.cc.o

.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cc.o:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.o
.PHONY : tests/test_http_server.cc.o

tests/test_http_server.i: tests/test_http_server.cc.i

.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cc.i:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.i
.PHONY : tests/test_http_server.cc.i

tests/test_http_server.s: tests/test_http_server.cc.s

.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cc.s:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.s
.PHONY : tests/test_http_server.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_socket.o: tests/test_socket.cc.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cc.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.o
.PHONY : tests/test_socket.cc.o

tests/test_socket.i: tests/test_socket.cc.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cc.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.i
.PHONY : tests/test_socket.cc.i

tests/test_socket.s: tests/test_socket.cc.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cc.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.s
.PHONY : tests/test_socket.cc.s

tests/test_tcp_server.o: tests/test_tcp_server.cc.o

.PHONY : tests/test_tcp_server.o

# target to build an object file
tests/test_tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.o
.PHONY : tests/test_tcp_server.cc.o

tests/test_tcp_server.i: tests/test_tcp_server.cc.i

.PHONY : tests/test_tcp_server.i

# target to preprocess a source file
tests/test_tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.i
.PHONY : tests/test_tcp_server.cc.i

tests/test_tcp_server.s: tests/test_tcp_server.cc.s

.PHONY : tests/test_tcp_server.s

# target to generate assembly for a file
tests/test_tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.s
.PHONY : tests/test_tcp_server.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

tests/test_uri.o: tests/test_uri.cc.o

.PHONY : tests/test_uri.o

# target to build an object file
tests/test_uri.cc.o:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cc.o
.PHONY : tests/test_uri.cc.o

tests/test_uri.i: tests/test_uri.cc.i

.PHONY : tests/test_uri.i

# target to preprocess a source file
tests/test_uri.cc.i:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cc.i
.PHONY : tests/test_uri.cc.i

tests/test_uri.s: tests/test_uri.cc.s

.PHONY : tests/test_uri.s

# target to generate assembly for a file
tests/test_uri.cc.s:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cc.s
.PHONY : tests/test_uri.cc.s

tests/test_util.o: tests/test_util.cc.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cc.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.o
.PHONY : tests/test_util.cc.o

tests/test_util.i: tests/test_util.cc.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cc.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.i
.PHONY : tests/test_util.cc.i

tests/test_util.s: tests/test_util.cc.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cc.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.s
.PHONY : tests/test_util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_uri"
	@echo "... test_http_connection"
	@echo "... echo_server"
	@echo "... test_tcp_server"
	@echo "... test_http_parser"
	@echo "... echo_server_udp"
	@echo "... test_scheduler"
	@echo "... test"
	@echo "... test_thread"
	@echo "... test_config"
	@echo "... test_bytearray"
	@echo "... test_util"
	@echo "... echo_udp_client"
	@echo "... test_fiber"
	@echo "... test_http_server"
	@echo "... test_address"
	@echo "... test_iomanager"
	@echo "... test_hook"
	@echo "... test_socket"
	@echo "... autoli"
	@echo "... test_http"
	@echo "... autoli/address.o"
	@echo "... autoli/address.i"
	@echo "... autoli/address.s"
	@echo "... autoli/bytearray.o"
	@echo "... autoli/bytearray.i"
	@echo "... autoli/bytearray.s"
	@echo "... autoli/config.o"
	@echo "... autoli/config.i"
	@echo "... autoli/config.s"
	@echo "... autoli/fd_manager.o"
	@echo "... autoli/fd_manager.i"
	@echo "... autoli/fd_manager.s"
	@echo "... autoli/fiber.o"
	@echo "... autoli/fiber.i"
	@echo "... autoli/fiber.s"
	@echo "... autoli/hook.o"
	@echo "... autoli/hook.i"
	@echo "... autoli/hook.s"
	@echo "... autoli/http/http.o"
	@echo "... autoli/http/http.i"
	@echo "... autoli/http/http.s"
	@echo "... autoli/http/http11_parser.rl.o"
	@echo "... autoli/http/http11_parser.rl.i"
	@echo "... autoli/http/http11_parser.rl.s"
	@echo "... autoli/http/http_connection.o"
	@echo "... autoli/http/http_connection.i"
	@echo "... autoli/http/http_connection.s"
	@echo "... autoli/http/http_parser.o"
	@echo "... autoli/http/http_parser.i"
	@echo "... autoli/http/http_parser.s"
	@echo "... autoli/http/http_server.o"
	@echo "... autoli/http/http_server.i"
	@echo "... autoli/http/http_server.s"
	@echo "... autoli/http/http_session.o"
	@echo "... autoli/http/http_session.i"
	@echo "... autoli/http/http_session.s"
	@echo "... autoli/http/httpclient_parser.rl.o"
	@echo "... autoli/http/httpclient_parser.rl.i"
	@echo "... autoli/http/httpclient_parser.rl.s"
	@echo "... autoli/http/servlet.o"
	@echo "... autoli/http/servlet.i"
	@echo "... autoli/http/servlet.s"
	@echo "... autoli/iomanager.o"
	@echo "... autoli/iomanager.i"
	@echo "... autoli/iomanager.s"
	@echo "... autoli/log.o"
	@echo "... autoli/log.i"
	@echo "... autoli/log.s"
	@echo "... autoli/mutex.o"
	@echo "... autoli/mutex.i"
	@echo "... autoli/mutex.s"
	@echo "... autoli/scheduler.o"
	@echo "... autoli/scheduler.i"
	@echo "... autoli/scheduler.s"
	@echo "... autoli/socket.o"
	@echo "... autoli/socket.i"
	@echo "... autoli/socket.s"
	@echo "... autoli/stream.o"
	@echo "... autoli/stream.i"
	@echo "... autoli/stream.s"
	@echo "... autoli/streams/socket_stream.o"
	@echo "... autoli/streams/socket_stream.i"
	@echo "... autoli/streams/socket_stream.s"
	@echo "... autoli/streams/zlib_stream.o"
	@echo "... autoli/streams/zlib_stream.i"
	@echo "... autoli/streams/zlib_stream.s"
	@echo "... autoli/tcp_server.o"
	@echo "... autoli/tcp_server.i"
	@echo "... autoli/tcp_server.s"
	@echo "... autoli/thread.o"
	@echo "... autoli/thread.i"
	@echo "... autoli/thread.s"
	@echo "... autoli/timer.o"
	@echo "... autoli/timer.i"
	@echo "... autoli/timer.s"
	@echo "... autoli/uri.rl.o"
	@echo "... autoli/uri.rl.i"
	@echo "... autoli/uri.rl.s"
	@echo "... autoli/util.o"
	@echo "... autoli/util.i"
	@echo "... autoli/util.s"
	@echo "... examples/echo_server.o"
	@echo "... examples/echo_server.i"
	@echo "... examples/echo_server.s"
	@echo "... examples/echo_server_udp.o"
	@echo "... examples/echo_server_udp.i"
	@echo "... examples/echo_server_udp.s"
	@echo "... examples/echo_udp_client.o"
	@echo "... examples/echo_udp_client.i"
	@echo "... examples/echo_udp_client.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http.o"
	@echo "... tests/test_http.i"
	@echo "... tests/test_http.s"
	@echo "... tests/test_http_connection.o"
	@echo "... tests/test_http_connection.i"
	@echo "... tests/test_http_connection.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcp_server.o"
	@echo "... tests/test_tcp_server.i"
	@echo "... tests/test_tcp_server.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_uri.o"
	@echo "... tests/test_uri.i"
	@echo "... tests/test_uri.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

